### ISSUE TITLE
Disabling MPO breaks Cyberpunk 2077

### ISSUE THREAD

**Issue by Simbiat** [RedDot-3ND7355/MPO-GPU-FIX#11]
Disabling MPO seems to be breaking Cyberpunk 2077 on 7900XTX. With MPO disabled after roughly 10-15 minutes it stops rendering parts of UI , world elements and even animations. The length probably depends on what you are doing and how you are traversing the world. I assume that fast travel or any other type of loading is not affected, but whenever there is texture streaming or something similar it breaks something. May be worth it adding a disclaimer to the wiki page.

**Comment by RedDot-3ND7355** [comment]
MPO Shouldn't be a problem on latest amd drivers. They have "seemed" to fix related issues on latest cards.
Check latest updates and see if there's any fixes done for cyberpunk 2077.

Disabling MPO always has and always will be a double edged sword on any games/apps using hardware acceleration.
