### ISSUE TITLE
Windows Defender doesn't like 5.2

### ISSUE THREAD

**Issue by BeerGogglesFTW** [RedDot-3ND7355/MPO-GPU-FIX#12]
![MPOGPUFIX](https://github.com/RedDot-3ND7355/MPO-GPU-FIX/assets/162273502/95a07dd7-94ef-4884-b0f2-c663e9b3c827)

I assume this is a false positive due to being an unknown zip file looking to make changes in Windows... but 5.1 worked fine.

**Comment by RedDot-3ND7355** [comment]
> ![MPOGPUFIX](https://private-user-images.githubusercontent.com/162273502/309986525-95a07dd7-94ef-4884-b0f2-c663e9b3c827.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjMzOTMsIm5iZiI6MTcwOTYyMzA5MywicGF0aCI6Ii8xNjIyNzM1MDIvMzA5OTg2NTI1LTk1YTA3ZGQ3LTk0ZWYtNDg4NC1iMGYyLWM2NjNlOWIzYzgyNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQwNzE4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNzc1NWU3YzVhZTFkZTY4NmY2NGFlNTBiODVjYjVlYWFjMjIxM2ViODNiNDY0M2VkZWFlNTk3MDE1ODhkZTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YYLxEiYKEJ2_tsCrSjAPoAx0oGytEfwM-8T__Taj8SY)
> 
> I assume this is a false positive due to being an unknown zip file looking to make changes in Windows... but 5.1 worked fine.

Yea clearly a false positive.
Don't know why it detects it as malware?
I only added a button and a link for donation on 5.2
The rest is all the same.

You can whitelist it or keep using 5.1
Since there ain't much of a difference anyways

**Comment by BeerGogglesFTW** [comment]
Thanks for the response. I had somebody else check, and their Windows Defender didn't flag it or find anything with a scan. Not sure why mine did.

Guess it happens randomly. Googled the issue, and only find one comment from a year ago, where somebody else's Windows Defender also flagged an older version of MPOGPUFIX I didn't have issues with.

Thanks again.
