### ISSUE TITLE
Can only see my integrated GPU from CPU instead of my GPU Actual

### ISSUE THREAD

**Issue by farske** [RedDot-3ND7355/MPO-GPU-FIX#13]
Hiya

I'm using a 13th Gen Core i5-13600k
32GB Ram
Sapphire Radeon Nitro+ 7900 XTX

It is only showing me my CPU-GPU

How do I change card see full options?

**Comment by RedDot-3ND7355** [comment]
> Hiya
> 
> I'm using a 13th Gen Core i5-13600k 32GB Ram Sapphire Radeon Nitro+ 7900 XTX
> 
> It is only showing me my CPU-GPU
> 
> How do I change card see full options?

Thanks for feedback!

Try disabling your APU in device manager the  reopen the tool to see if it works.

If not, I'll need a couple info once I get home.
So we can work this out properly and push a fix :)

**Comment by farske** [comment]
Disabling and uninstalling got me around this, thanks for the obvious idea! haha

Now I can reinstall!

**Comment by RedDot-3ND7355** [comment]
> Disabling and uninstalling got me around this, thanks for the obvious idea! haha
> 
> Now I can reinstall!

Great! 

Also, quick question, what was the name of the gpu shown(exact name)? Or any other details I could use to prevent users from having to do this :)

**Comment by CloudShady** [comment]
Hi!
Facing the same issue here
Any way i can make the application choose my dGPU instead of my iGPU without having to reinstall?

**Comment by RedDot-3ND7355** [comment]
> Hi! Facing the same issue here Any way i can make the application choose my dGPU instead of my iGPU without having to reinstall?

quick question, what was the name of the gpu shown(exact name)? Or any other details I could use to prevent users from having to do this :)

**Comment by farske** [comment]
Sorry, didnt see reply.

It says UNKWN GPU

But the GPU also shows you its a Inte(R) UHD Graphics 770
see: https://i.imgur.com/fkpwioj.png

**Comment by CloudShady** [comment]
Mine gives me this
Also side note, i have custom AMD drivers from Amernimezone that i use, so it identfies as RX Vega Graphics
But its the iGPU of the Ryzen 7 4800H
![image](https://github.com/RedDot-3ND7355/MPO-GPU-FIX/assets/111050194/c871b6de-bc14-476f-9443-dea79b7375c0)

**Comment by RedDot-3ND7355** [comment]
> Mine gives me this Also side note, i have custom AMD drivers from Amernimezone that i use, so it identfies as RX Vega Graphics But its the iGPU of the Ryzen 7 4800H ![image](https://private-user-images.githubusercontent.com/111050194/329331240-c871b6de-bc14-476f-9443-dea79b7375c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2OTg1NDcsIm5iZiI6MTcxNTY5ODI0NywicGF0aCI6Ii8xMTEwNTAxOTQvMzI5MzMxMjQwLWM4NzFiNmRlLWJjMTQtNDc2Zi05NDQzLWRlYTc5YjczNzVjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxNDUwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzNjOGU0YjNlNjUyNWEzZjY3MWE0ZTVhMzQ1MTAzMzkyNjllMDVjNDQ0YjMwYzBjNzg1OTYyMjA1M2Y5NjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DczgnsgCBHYYCsoLkBQ0yN5XGwdt--QDJEXJnCEtcVw)

Thanks for the feedback! I'll be able to push an update this weekend for both my tools ♥️


Notes for self:
- Filter non 56/64 vega gpu.
- Filter apu for integrated intel graphics

**Comment by RedDot-3ND7355** [comment]
v6.0 released <3
