### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by HamzaETTH** [RedDot-3ND7355/MPO-GPU-FIX#14]
Not an issue, just wanted to thank you for this. I've had this issue for a while (stutter after alt-tab). I've tried a lot of things (gsync, mouse polling etc)  It didn't happen in all games. Not in Hitman, Overwatch, sometimes in Helldivers 2 but always in Chivalry 2, Deep Rock Galactic and Fortnite. I've only tested in Chivalry 2 but it seem like this is fixed.

Just for reference:
2070 Super
AMD Ryzen 5800X3D
32 GB RAM

**Comment by RedDot-3ND7355** [comment]
You're welcome <3 Glad it was able to help :)
