### ISSUE TITLE
Doesn't work on Windows 10 Enterprise LTSC 2021 after version 4.0

### ISSUE THREAD

**Issue by compieter-gh** [RedDot-3ND7355/MPO-GPU-FIX#15]
When trying to open the application on Windows 10 Enterprise LTSC 2021

It give this error in reliability history and never launches.

Faulting application name: MPOGPUFIX.exe, version: 6.1.0.0, time stamp: 0xc2c6aad2
Faulting module name: KERNELBASE.dll, version: 10.0.19041.4412, time stamp: 0x6d8c3da8
Exception code: 0xe0434352
Fault offset: 0x00140b82
Faulting process id: 0x5f84
Faulting application start time: 0x01dab04735088bdd
Faulting application path: D:\Users\Pieter\Downloads\MPOGPUFIX\MPOGPUFIX.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: e7943bcb-dee2-4a26-ac09-64a551148b34
Faulting package full name: 
Faulting package-relative application ID: 

Only version that seems to work is 4.0 after that every version fails to launch.

**Comment by RedDot-3ND7355** [comment]
Can you get another log? It's either below or above the one you posted. That log will provide me info on where it occured.

Edit: Might be shader cache, what's your gpu?

**Comment by compieter-gh** [comment]
.NET Runtime:

Application: MPOGPUFIX.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Security.SecurityException
   at System.ThrowHelper.ThrowSecurityException(System.ExceptionResource)
   at Microsoft.Win32.RegistryKey.OpenSubKey(System.String, Boolean)
   at AMDGPUFIX.SHADERCACHE.CheckShaderCache()
   at AMDGPUFIX.Form1.DetectSHADERCACHE()
   at AMDGPUFIX.Form1..ctor()
   at AMDGPUFIX.Preload..ctor()
   at AMDGPUFIX.Program.Main()

**Comment by compieter-gh** [comment]
I am using a RX 6800 but also had this happen in the past with the RX 6600 XT

**Comment by RedDot-3ND7355** [comment]
> I am using a RX 6800 but also had this happen in the past with the RX 6600 XT

I'll revise the checkshadercache, your reg input prob doesnt exist
havent added a proper check for that

**Comment by compieter-gh** [comment]
Okay, thank you.

**Comment by RedDot-3ND7355** [comment]
[MPOGPUFIX.zip](https://github.com/RedDot-3ND7355/MPO-GPU-FIX/files/15478951/MPOGPUFIX.zip)
Here's the test build, let me know if this solved it! :)

IF not, please post the error image again (just in case it breaks again)

**Comment by compieter-gh** [comment]
Faulting application name: MPOGPUFIX.exe, version: 6.2.0.0, time stamp: 0xcd36a19f
Faulting module name: KERNELBASE.dll, version: 10.0.19041.4412, time stamp: 0x6d8c3da8
Exception code: 0xe0434352
Fault offset: 0x00140b82
Faulting process id: 0x4700
Faulting application start time: 0x01dab1b5adf1c28b
Faulting application path: D:\Users\Pieter\Downloads\MPOGPUFIX\MPOGPUFIX.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 13f5fe03-61c6-4acf-825f-96956f07d311
Faulting package full name: 
Faulting package-relative application ID: 

Application: MPOGPUFIX.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Security.SecurityException
   at System.ThrowHelper.ThrowSecurityException(System.ExceptionResource)
   at Microsoft.Win32.RegistryKey.OpenSubKey(System.String, Boolean)
   at AMDGPUFIX.SHADERCACHE.CheckShaderCache()
   at AMDGPUFIX.Form1.DetectSHADERCACHE()
   at AMDGPUFIX.Form1..ctor()
   at AMDGPUFIX.Preload..ctor()
   at AMDGPUFIX.Program.Main()

**Comment by compieter-gh** [comment]
Just did some digging myself and checked the code and idk if its the check itself if i am understanding it correctly.
Its unable to open the Properties string as its throwing a Access denied which is lining up with what am seeing in the Exception Info.

Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\Properties

Hope this is usefull.

![image](https://github.com/RedDot-3ND7355/MPO-GPU-FIX/assets/34034571/70fb7474-4f01-4707-94b1-e33dca101b72)

**Comment by RedDot-3ND7355** [comment]
> Just did some digging myself and checked the code and idk if its the check itself if i am understanding it correctly. Its unable to open the Properties string as its throwing a Access denied which is lining up with what am seeing in the Exception Info.
> 
> Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class{4d36e968-e325-11ce-bfc1-08002be10318}\Properties
> 
> Hope this is usefull.
> 
> ![image](https://private-user-images.githubusercontent.com/34034571/334779341-70fb7474-4f01-4707-94b1-e33dca101b72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMjYzMjYsIm5iZiI6MTcxNzAyNjAyNiwicGF0aCI6Ii8zNDAzNDU3MS8zMzQ3NzkzNDEtNzBmYjc0NzQtNGYwMS00NzA3LTk0YjEtZTMzZGNhMTAxYjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDIzNDAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhNDlkZjk4N2ZkYzc5YzhiODI0NTBmMGIwMjM4ODViNzE3NzdjOTAxZWZmNzI0YTJmNmI1NjdhZTU4MjAwM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uAxEjF9Ruz8dZ87dIBADC5qToHFbjho-NKT9UiTIzZk)

Thanks for digging into it, I've been wrecking my brain trying to figure out why it's not working. Turns out your Windows is preventing you from accessing your amd driver properties.

I can add a handle for the exception but sadly can't do anything about it. You'll have to find out why it's preventing you access.

I personally suspect you have a virus on your pc. OR some other tools that were used, i have no idea tbh. 
Use this to get rid of any rootkit virus you might have: https://www.malwarebytes.com/solutions/rootkit-scanner

Best of luck!

**Comment by compieter-gh** [comment]
Reinstalled the driver and while it was uninstalled i was able to run it but then after the reinstall same issue apeared again
also i already have malwarebytes and my system is clean
Im thinking maybe something todo with LTSC? i will have to do further digging.

**Comment by compieter-gh** [comment]
If you can add a check that woulde be nice.

**Comment by RedDot-3ND7355** [comment]
> If you can add a check that woulde be nice.

I'll upload a test build for ya after work 👌

Edit: Did more digging and your Enterprise LTSC has lots of things removed such as access to many of the registry and more.
To solve the problem, you'd require hopping off LTSC and go to a regular windows 10 enterprise build.

I'll still upload a test build later today 👌

**Comment by compieter-gh** [comment]
Might also be the source off other issues i have been having then maybe. like a lot of driver crashes. (As its not validated for LTSC)

**Comment by compieter-gh** [comment]
> > If you can add a check that woulde be nice.
> 
> I'll upload a test build for ya after work 👌
> 
> Edit: Did more digging and your Enterprise LTSC has lots of things removed such as access to many of the registry and more. To solve the problem, you'd require hopping off LTSC and go to a regular windows 10 enterprise build.
> 
> I'll still upload a test build later today 👌

Did find a solution to be able too access it

https://qtechbabble.wordpress.com/2021/04/23/run-regedit-as-system-user-to-circumvent-windows-registry-access-denied-errors/

but idk if that is usefull

**Comment by RedDot-3ND7355** [comment]
> > > If you can add a check that woulde be nice.
> > 
> > 
> > I'll upload a test build for ya after work 👌
> > Edit: Did more digging and your Enterprise LTSC has lots of things removed such as access to many of the registry and more. To solve the problem, you'd require hopping off LTSC and go to a regular windows 10 enterprise build.
> > I'll still upload a test build later today 👌
> 
> Did find a solution to be able too access it
> 
> https://qtechbabble.wordpress.com/2021/04/23/run-regedit-as-system-user-to-circumvent-windows-registry-access-denied-errors/
> 
> but idk if that is usefull

Found that article earlier too. Would be relevant if the issue was regedit.exe app itself.
But not the case for us, as we use windows API to do all the work.

**Comment by compieter-gh** [comment]
dammit i do kinda wanna stay on windows 10 for longer than 2025 though (main reason for using it along with the stability gain)
I dont like regulair windows 10/11 as i have been on it before and well just more or less felt like a step back.
Is there any other way than using the registery to detect it im guessing not right?
or is there maybe a way to launch regardless when there is an error (ofc the error still be shown) or with flags to disable/bypass the check?

Might be able to try upgradeing to the latest LTSC 2024 see if that helps or see if i can do an in place upgrade when using the product spoofing to switch to a regulair version. as i also rather not reinstall everything if i dont have too which will likely take me days.

**Comment by RedDot-3ND7355** [comment]
> dammit i do kinda wanna stay on windows 10 for longer than 2025 though (main reason for using it along with the stability gain) I dont like regulair windows 10/11 as i have been on it before and well just more or less felt like a step back. Is there any other way than using the registery to detect it im guessing not right? or is there maybe a way to launch regardless when there is an error (ofc the error still be shown) or with flags to disable/bypass the check?
> 
> Might be able to try upgradeing to the latest LTSC 2024 see if that helps or see if i can do an in place upgrade when using the product spoofing to switch to a regulair version. as i also rather not reinstall everything if i dont have too which will likely take me days.

Yea sadly the only solution would be to switch windows to have the shadercache option. As it's driver-level configs, LTSC denies access to it.

Once I have the test build ready in about 5-6 hours you'll be able to use the app but won't be able to use the shader cache dropdown to prevent any issues.

**Comment by compieter-gh** [comment]
Thank you

**Comment by RedDot-3ND7355** [comment]
> Thank you

Here's a test build! Let me know if it works and shader cache should be disabled :)

[MPOGPUFIX.zip](https://github.com/user-attachments/files/15506562/MPOGPUFIX.zip)

**Comment by compieter-gh** [comment]
Yes it works! Thank you.

**Comment by RedDot-3ND7355** [comment]
> Yes it works! Thank you.

Glad it worked! Will push the changes for that sooner or later, just gotta fix this issue with the other ticket 😁👌

**Comment by compieter-gh** [comment]
@RedDot-3ND7355  
Its not Windows 10/11 LTSC's issue i tested it on a fresh install and it just works. 
So its something with my install thats causing that. which am looking into atm.
Likely something i installed/Modified. Maybe indeed a virus but undetected?

**Comment by RedDot-3ND7355** [comment]
> @RedDot-3ND7355 Its not Windows 10/11 LTSC's issue i tested it on a fresh install and it just works. So its something with my install thats causing that. which am looking into atm. Likely something i installed/Modified. Maybe indeed a virus but undetected?

aaah, then yea logically a fresh install would solve that issue (if it was a virus/rootkit virus)
The virus could also be a source of any problems you were having. 

ps: I'll modify the popup message to make sure it doesnt confuse anyone 😉

**Comment by compieter-gh** [comment]
Yeah thank you. I will investigate this and see if i can figure out where its coming from. 
I did have this in the past aswell but probably was the same install now am thinking of it.

**Comment by compieter-gh** [comment]
Its Acronis True Image OEM

Even tough i have turned off the protection on it its still causing issues.
Disabled all services of it and seemed to resolve the issue. 
![image](https://github.com/RedDot-3ND7355/MPO-GPU-FIX/assets/34034571/ab1b0c44-e3fe-4ce8-8c48-019bee060fe0)
![TrueImage_jHcAeMVndc](https://github.com/RedDot-3ND7355/MPO-GPU-FIX/assets/34034571/37a0051e-ed74-4956-af20-a548224b0d0b)

After starting it when the services are disabled it causes the issue again.

**Comment by RedDot-3ND7355** [comment]
> Its Acronis True Image OEM
> 
> Even tough i have turned off the protection on it its still causing issues. Disabled all services of it and seemed to resolve the issue. ![image](https://private-user-images.githubusercontent.com/34034571/335893986-ab1b0c44-e3fe-4ce8-8c48-019bee060fe0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNTgwNjUsIm5iZiI6MTcxNzM1Nzc2NSwicGF0aCI6Ii8zNDAzNDU3MS8zMzU4OTM5ODYtYWIxYjBjNDQtZTNmZS00Y2U4LThjNDgtMDE5YmVlMDYwZmUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDE5NDkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzZmIzZWQ1MTI1YWU2NDI5M2FjMzliZWQxMTQ5ZWM1MzQ2OTI4NDkxZDI4MzA3M2EzNTIyYzM2YTQ1MmI1MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NPvpDX4zjzvjbfgNzFMnnEYwjkQCw7f4AOy1H16C9Fs) ![TrueImage_jHcAeMVndc](https://private-user-images.githubusercontent.com/34034571/335894029-37a0051e-ed74-4956-af20-a548224b0d0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNTgwNjUsIm5iZiI6MTcxNzM1Nzc2NSwicGF0aCI6Ii8zNDAzNDU3MS8zMzU4OTQwMjktMzdhMDA1MWUtZWQ3NC00OTU2LWFmMjAtYTU0ODIyNGIwZDBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDE5NDkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMzgxNzUyNzQ0NGVjNWM0NTgzOGQ0NTdlNWY0MmMyN2FmZGFhYjAxZjJlMTU4MjVlZGM5ODI0ZjVmNTEzMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QEcBDry3RDg3Y-unLLhs3FYQWhzYfQ8Hx0eavI4o99M)
> 
> After starting it when the services are disabled it causes the issue again.

Wow, that's a pain. Good protection against viruses in registry I guess preventing important stuff from being modified? Double edged sword tho.

**Comment by compieter-gh** [comment]
Yeah digged some more and indeed seems to be the protection again ransomware

Acronis Active Protection (TM) Service
"C:\Program Files (x86)\Common Files\Acronis\ActiveProtection\anti_ransomware_service.exe"

Yet its disabled in the app it still runs the service. So id say thats a bug.

**Comment by compieter-gh** [comment]
Looked it up and apparently am not the only one who's having this issue.
https://forum.acronis.com/forum/acronis-cyber-protect-home-office-forum/can-anti-malware-now-be-turned?ckattempt=1

**Comment by RedDot-3ND7355** [comment]
> Looked it up and apparently am not the only one who's having this issue. https://forum.acronis.com/forum/acronis-cyber-protect-home-office-forum/can-anti-malware-now-be-turned?ckattempt=1

i see that it's been an issue for years with Acronis. That's saddening.
