### ISSUE TITLE
How to switching the GPU

### ISSUE THREAD

**Issue by AntaresPolestar** [RedDot-3ND7355/MPO-GPU-FIX#16]
I have two graphics cards, the program runs on the Nvidia graphics card by default, and it doesn't work to disable the Nvidia graphics card, so how should this tool switch graphics cards?
![屏幕截图 2024-05-28 192508](https://github.com/RedDot-3ND7355/MPO-GPU-FIX/assets/120145857/3f202d6a-965d-4ca8-8865-6780c668cd00)
![屏幕截图 2024-05-28 192708](https://github.com/RedDot-3ND7355/MPO-GPU-FIX/assets/120145857/d0dcc09f-8e79-4749-867b-37c6efbe1638)

**Comment by RedDot-3ND7355** [comment]
It's fine. The changes applied does not rely on your card detected, they are applied to windows. 

So you can use the tool anyway unless you really want to use turn off amd's ULPS. 👌

PS: I can still add a feature to blacklist cards you don't want detected as a button?

**Comment by AntaresPolestar** [comment]
Thank you for your answers.

These features are sufficient。

This software is useful!

**Comment by RedDot-3ND7355** [comment]
Thanks a lot! ♥️

If you tried with the device disabled and still appeared, I will be adding a way to detect if the gpu is deactivated to automatically skip it.

**Comment by RedDot-3ND7355** [comment]
@AntaresPolestar Here's a test build, let me know if it works. 
-redacted-

**Comment by AntaresPolestar** [comment]
ops...

**Comment by AntaresPolestar** [comment]
> @AntaresPolestar Here's a test build, let me know if it works. -redacted-

It won't work.

Unresponsive when I clicked it .The official version can be used normally.

**Comment by RedDot-3ND7355** [comment]
> > @AntaresPolestar Here's a test build, let me know if it works. -redacted-
> 
> It won't work.
> 
> Unresponsive when I clicked it .The official version can be used normally.

Here's a new test build! :)
This one should work just fine!

[MPOGPUFIX.zip](https://github.com/RedDot-3ND7355/MPO-GPU-FIX/files/15491788/MPOGPUFIX.zip)

**Comment by RedDot-3ND7355** [comment]
@AntaresPolestar just making sure you received my message and tested the app. Need a little feedback before pushing out the changes made :)

**Comment by AntaresPolestar** [comment]
Sry.I received it but forget reply.

![屏幕截图 2024-05-31 172233](https://github.com/RedDot-3ND7355/MPO-GPU-FIX/assets/120145857/ca72dcef-e642-4a75-816c-8387187aaab9)

I've disabled the NVIDIA card and restarted the computer, but he still didn't skip the disabled device.

**Comment by RedDot-3ND7355** [comment]
> Sry.I received it but forget reply.
> 
> ![屏幕截图 2024-05-31 172233](https://private-user-images.githubusercontent.com/120145857/335521344-ca72dcef-e642-4a75-816c-8387187aaab9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNzM0MzcsIm5iZiI6MTcxNzE3MzEzNywicGF0aCI6Ii8xMjAxNDU4NTcvMzM1NTIxMzQ0LWNhNzJkY2VmLWU2NDItNGE3NS04MTZjLTgzODcxODdhYWFiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQxNjMyMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Zjc0NzBmZmJlZjUyZWYyYmYxMWRlYWNlYmIyODhhOTUwMDFlYzZlNDNjN2I4OTU2Zjc0MmQ2ZDY1YjZlNzAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T7gD5e3Rdahqmq-RufpQyTivADblKPX6DDNmZG8x9ns)
> 
> I've disabled the NVIDIA card and restarted the computer, but he still didn't skip the disabled device.

Will give you a test build that will dump information about ur gpu so I can see how I can check the status 👌

**Comment by RedDot-3ND7355** [comment]
@AntaresPolestar  Here's another build, this one will create a file called 0.dump and more if any.
Please send me all the dump files so I can track down where I can check the status of your card and add that to the detection method <3
[MPOGPUFIX.zip](https://github.com/user-attachments/files/15520562/MPOGPUFIX.zip)

**Comment by AntaresPolestar** [comment]
> @AntaresPolestar Here's another build, this one will create a file called 0.dump and more if any. Please send me all the dump files so I can track down where I can check the status of your card and add that to the detection method <3 [MPOGPUFIX.zip](https://github.com/user-attachments/files/15520562/MPOGPUFIX.zip)

This build have same problem like last time.It unresponsive(⊙︿⊙)

**Comment by RedDot-3ND7355** [comment]
> > @AntaresPolestar Here's another build, this one will create a file called 0.dump and more if any. Please send me all the dump files so I can track down where I can check the status of your card and add that to the detection method <3 [MPOGPUFIX.zip](https://github.com/user-attachments/files/15520562/MPOGPUFIX.zip)
> 
> This build have same problem like last time.It unresponsive(⊙︿⊙)

Oh then I think ur antivirus (windows defender) is blocking it. Can you check the logs on event viewer to see what's happening with the app? 

There should be an error log and an info log about the error 

Here's how to get it:

Type “Event Viewer” to Windows Search > Open application.
Go to “Windows Logs” > Application.
Look for Date and Time when Simulator crashed > Level should be: Error and Source: Application Error.

**Comment by AntaresPolestar** [comment]
> > > 这是另一个版本，这个版本将创建一个名为 0.dump 的文件，如果有的话，还会有更多。请将所有转储文件发送给我，以便我可以找到可以检查您卡状态的位置，并将其添加到检测方法 <3 [MPOGPUFIX.zip](https://github.com/user-attachments/files/15520562/MPOGPUFIX.zip)
> > 
> > 
> > 此版本有与上次相同的问题。它无响应（⊙〈⊙）
> 
> 哦，那么我认为您的防病毒软件（Windows Defender）正在阻止它。您可以检查事件查看器上的日志以查看应用程序发生了什么吗？
> 
> 应该有一个错误日志和一个关于错误的信息日志
> 
> 获取方法如下：
> 
> 键入“事件查看器”到 Windows Search > Open 应用程序。转到应用程序>“Windows 日志”。查找模拟器崩溃的日期和时间>级别应为：错误和源：应用程序错误。

![image](https://github.com/RedDot-3ND7355/MPO-GPU-FIX/assets/120145857/3f4e3bdd-3bb3-45f6-8e19-a54917e127a7)
![image](https://github.com/RedDot-3ND7355/MPO-GPU-FIX/assets/120145857/07234861-f2c2-4b6f-8af1-70c4696107ce)
![image](https://github.com/RedDot-3ND7355/MPO-GPU-FIX/assets/120145857/edfde136-ca2b-42d0-9a20-1544c1ae1130)



My Windows Defender not enabled.Exit the other defender can't start.

**Comment by RedDot-3ND7355** [comment]
> > > > 这是另一个版本，这个版本将创建一个名为 0.dump 的文件，如果有的话，还会有更多。请将所有转储文件发送给我，以便我可以找到可以检查您卡状态的位置，并将其添加到检测方法 <3 [MPOGPUFIX.zip](https://github.com/user-attachments/files/15520562/MPOGPUFIX.zip)
> > > 
> > > 
> > > 此版本有与上次相同的问题。它无响应（⊙〈⊙）
> > 
> > 
> > 哦，那么我认为您的防病毒软件（Windows Defender）正在阻止它。您可以检查事件查看器上的日志以查看应用程序发生了什么吗？
> > 应该有一个错误日志和一个关于错误的信息日志
> > 获取方法如下：
> > 键入“事件查看器”到 Windows Search > Open 应用程序。转到应用程序>“Windows 日志”。查找模拟器崩溃的日期和时间>级别应为：错误和源：应用程序错误。
> 
> ![image](https://private-user-images.githubusercontent.com/120145857/335853413-3f4e3bdd-3bb3-45f6-8e19-a54917e127a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzE5MzIsIm5iZiI6MTcxNzMzMTYzMiwicGF0aCI6Ii8xMjAxNDU4NTcvMzM1ODUzNDEzLTNmNGUzYmRkLTNiYjMtNDVmNi04ZTE5LWE1NDkxN2UxMjdhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQxMjMzNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDAyMTJmNmNiOTU0NWYzMzNiYmViOWI4MTI5YzM5Y2FhMGZiYzM0M2NkNzdlNjMzNTljYjE2MmY1ZjQ1MzU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w36y2jeSTznz9DW_ehndbKYECegEU4K8yrTqp9_syHQ) ![image](https://private-user-images.githubusercontent.com/120145857/335853434-07234861-f2c2-4b6f-8af1-70c4696107ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzE5MzIsIm5iZiI6MTcxNzMzMTYzMiwicGF0aCI6Ii8xMjAxNDU4NTcvMzM1ODUzNDM0LTA3MjM0ODYxLWYyYzItNGI2Zi04YWYxLTcwYzQ2OTYxMDdjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQxMjMzNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTY5NWJlNjc5MzA3MTZmZjFhMmJhZmVlMjM2MzJjMmY1ODUzOWMwODdhN2Q1Y2NiMDY1ZGM4OWZlYWVmNWZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B-ryh01KMqK7M3IRiSjZfoY46gYEJ6k-ba0m9ioDJvU) ![image](https://private-user-images.githubusercontent.com/120145857/335853444-edfde136-ca2b-42d0-9a20-1544c1ae1130.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzE5MzIsIm5iZiI6MTcxNzMzMTYzMiwicGF0aCI6Ii8xMjAxNDU4NTcvMzM1ODUzNDQ0LWVkZmRlMTM2LWNhMmItNDJkMC05YTIwLTE1NDRjMWFlMTEzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQxMjMzNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODZiMmU5YmRjYzk3ZjgxZDcxNGM5NjZjNWM0ZmZkZDI4ZTY0ZmI4ZWYwNTA2OWI5OTQyOGNiZmI4ZTg3NTNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MlD33kcf4hf3arc24_0H8qUF-zpeWIqid9VZpf45hG8)
> 
> My Windows Defender not enabled.Exit the other defender can't start.

Thanks for the error log! I forgot to upload the dll files for the dumping to work 

Here's the files you need to extract and put in the same folder as mpogpufix.exe

[Newtonsoft.Json.zip](https://github.com/user-attachments/files/15525312/Newtonsoft.Json.zip)

**Comment by AntaresPolestar** [comment]
> > > > > 这是另一个版本，这个版本将创建一个名为 0.dump 的文件，如果有的话，还会有更多。请将所有转储文件发送给我，以便我可以找到可以检查您卡状态的位置，并将其添加到检测方法 <3 [MPOGPUFIX.zip](https://github.com/user-attachments/files/15520562/MPOGPUFIX.zip)
> > > > 
> > > > 
> > > > 此版本有与上次相同的问题。它无响应（⊙〈⊙）
> > > 
> > > 
> > > 哦，那么我认为您的防病毒软件（Windows Defender）正在阻止它。您可以检查事件查看器上的日志以查看应用程序发生了什么吗？
> > > 应该有一个错误日志和一个关于错误的信息日志
> > > 获取方法如下：
> > > 键入“事件查看器”到 Windows Search > Open 应用程序。转到应用程序>“Windows 日志”。查找模拟器崩溃的日期和时间>级别应为：错误和源：应用程序错误。
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/120145857/335853413-3f4e3bdd-3bb3-45f6-8e19-a54917e127a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzE5MzIsIm5iZiI6MTcxNzMzMTYzMiwicGF0aCI6Ii8xMjAxNDU4NTcvMzM1ODUzNDEzLTNmNGUzYmRkLTNiYjMtNDVmNi04ZTE5LWE1NDkxN2UxMjdhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQxMjMzNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDAyMTJmNmNiOTU0NWYzMzNiYmViOWI4MTI5YzM5Y2FhMGZiYzM0M2NkNzdlNjMzNTljYjE2MmY1ZjQ1MzU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w36y2jeSTznz9DW_ehndbKYECegEU4K8yrTqp9_syHQ) ![image](https://private-user-images.githubusercontent.com/120145857/335853434-07234861-f2c2-4b6f-8af1-70c4696107ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzE5MzIsIm5iZiI6MTcxNzMzMTYzMiwicGF0aCI6Ii8xMjAxNDU4NTcvMzM1ODUzNDM0LTA3MjM0ODYxLWYyYzItNGI2Zi04YWYxLTcwYzQ2OTYxMDdjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQxMjMzNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTY5NWJlNjc5MzA3MTZmZjFhMmJhZmVlMjM2MzJjMmY1ODUzOWMwODdhN2Q1Y2NiMDY1ZGM4OWZlYWVmNWZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B-ryh01KMqK7M3IRiSjZfoY46gYEJ6k-ba0m9ioDJvU) ![image](https://private-user-images.githubusercontent.com/120145857/335853444-edfde136-ca2b-42d0-9a20-1544c1ae1130.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzE5MzIsIm5iZiI6MTcxNzMzMTYzMiwicGF0aCI6Ii8xMjAxNDU4NTcvMzM1ODUzNDQ0LWVkZmRlMTM2LWNhMmItNDJkMC05YTIwLTE1NDRjMWFlMTEzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQxMjMzNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODZiMmU5YmRjYzk3ZjgxZDcxNGM5NjZjNWM0ZmZkZDI4ZTY0ZmI4ZWYwNTA2OWI5OTQyOGNiZmI4ZTg3NTNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MlD33kcf4hf3arc24_0H8qUF-zpeWIqid9VZpf45hG8)
> > My Windows Defender not enabled.Exit the other defender can't start.
> 
> Thanks for the error log! I forgot to upload the dll files for the dumping to work
> 
> Here's the files you need to extract and put in the same folder as mpogpufix.exe
> 
> [Newtonsoft.Json.zip](https://github.com/user-attachments/files/15525312/Newtonsoft.Json.zip)

![image](https://github.com/RedDot-3ND7355/MPO-GPU-FIX/assets/120145857/d7959abb-eafa-4a9f-9671-3c15325e8ed2)

**Comment by AntaresPolestar** [comment]
![image](https://github.com/RedDot-3ND7355/MPO-GPU-FIX/assets/120145857/0aeb3bb3-64e7-4da1-95ee-46beb72c9c7d)

[0.zip](https://github.com/user-attachments/files/15525391/0.zip)

**Comment by RedDot-3ND7355** [comment]
> ![image](https://private-user-images.githubusercontent.com/120145857/335866683-0aeb3bb3-64e7-4da1-95ee-46beb72c9c7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzM1NTksIm5iZiI6MTcxNzMzMzI1OSwicGF0aCI6Ii8xMjAxNDU4NTcvMzM1ODY2NjgzLTBhZWIzYmIzLTY0ZTctNGRhMS05NWVlLTQ2YmViNzJjOWM3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQxMzAwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZmY3Y2Y5NjNhYTE3OGU3MzY2Y2NmN2Q0ODM4OTZiZDE5YzEyYzExMWM3NjA3Y2Q1NWI2MTU5Y2FjYjQwY2IxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4qtuFeIsRDrKgoXVBbc3cpI15dn1JDLFqgvJr1f2ADo)
> 
> [0.zip](https://github.com/user-attachments/files/15525391/0.zip)

Thanks! Here's a new build and should work fine now! 👍 

[MPOGPUFIX.zip](https://github.com/user-attachments/files/15525765/MPOGPUFIX.zip)

**Comment by AntaresPolestar** [comment]
Thanks for your hard work!

I want know how it work,It just skip the NVIDIA device or skip the disabled device?

**Comment by RedDot-3ND7355** [comment]
> Thanks for your hard work!
> 
> I want know how it work,It just skip the NVIDIA device or skip the disabled device?

Skips disabled device / Off line.
Enable the device and see if it sets back to nvidia.

**Comment by RedDot-3ND7355** [comment]
I'll assume everything is working as intended! Thanks for your patience and testing 😁

If there's still an issue, feel free to reopen the ticket 😉👌
