### ISSUE TITLE
Ambiguous information about TDRLevel in Wiki

### ISSUE THREAD

**Issue by KurzedMetal** [RedDot-3ND7355/MPO-GPU-FIX#17]
The [TDRLevel wiki](../wiki/TDRLevel) mentions: `Setting TDRLevel to "Def" (Default) will trigger your TDR to fix the crashes caused by gpu drivers and other errors on NVIDIA(mostly) & AMD GPUs.`

But i thought part of the issue is actually TDR trying to fix driver issues that generated a problem, so, as a user of the tool, should I set to "Def" or stay away from it? IMO it would be nice if the documentation is clearer about this setting, maybe list all the possible values and what they do for us.

Also: I'm super happy I found your tool and documentation explaining these issues, I've been having random gpu drivers crashes (amd) forever and I never managed to find the root cause. And I'm a dev / tech savvy person that read tons of info in internet. People need more awareness about this subject. Thanks for your work!

**Comment by RedDot-3ND7355** [comment]
I will update the wiki section about tdrlevel and will be including important parts of the documentation :)

Having tdrlevel set to none by default and not using the actual default value will do the same thing 👌

So you don't have to touch it at all if it's set to none 😁

**Comment by RedDot-3ND7355** [comment]
Updated it 👍 

thanks for the feedback! Really appreciated <3

**Comment by KurzedMetal** [comment]
Much better, thanks! considered this closed.
