### ISSUE TITLE
Exe file?

### ISSUE THREAD

**Issue by Colin1374** [RedDot-3ND7355/MPO-GPU-FIX#6]
How do I actually run this tool? I've downloaded the zip file > extracted but don't see instructions on which tool to actually run? Is there supposed to be an exe file?

**Comment by RedDot-3ND7355** [comment]
On the main page of the repo, there are releases on the right side.
Which leads to here: https://github.com/RedDot-3ND7355/MPO-GPU-FIX/releases/tag/Hotfix1
From there you can download the zip: https://github.com/RedDot-3ND7355/MPO-GPU-FIX/releases/download/Hotfix1/MPOGPUFIX.zip

From there you can extract and run the tool :)
