### ISSUE TITLE
MPO disabled is not compatible with the Netflix App (UWP)

### ISSUE THREAD

**Issue by mann1x** [RedDot-3ND7355/MPO-GPU-FIX#7]
Disabling MPO will cause video issues (broken video with flashing out of sequence frames) on the Netflix App when in full-screen mode.
Tested on Windows 10.

**Comment by RedDot-3ND7355** [comment]
@mann1x tried disabling Freesync from monitor and in amd software while having MPO fix on?

**Comment by mann1x** [comment]
Oh sorry didn't specify, the GPU is an nVidia RTX 3090.
Disabling G-Sync didn't help.

**Comment by RedDot-3ND7355** [comment]
@mann1x does using Netflix from browser work fine?

If you really want to use the app. 
I'd recommend doing a DDU then reinstall your nvidia drivers with NVClean install.
Let me know if that solves it. (make sure you got the latest whql update)

**Comment by mann1x** [comment]
Sorry didn't tested it.
I have never used it from the browser here.
At the first occasion will try again.
Pretty sure MPC-HC with madVr didn't have any issue.
