### ISSUE TITLE
Getting Unknown GPU on RX580 23.4.1 driver

### ISSUE THREAD

**Issue by gutko** [RedDot-3ND7355/MPO-GPU-FIX#8]
Also the red link button does nothing and is like inactive
![Screenshot 2023-04-13 204853](https://user-images.githubusercontent.com/1101181/231855235-e66282b2-db37-43cc-8931-85fc6fd72db5.png)

**Comment by RedDot-3ND7355** [comment]
Don't mind it, I simply did not added a string check for amd radeon's that doesn't have a "amd" in it. :)

Unless you really want to disable the ULPS. Let me know and I'll update it!

**Comment by gutko** [comment]
please do if its not too much hassle. thank you!

**Comment by RedDot-3ND7355** [comment]
> please do if its not too much hassle. thank you!

Sorry for such a late reply, I'll be able to fix this bug next tuesday and I will be adding a new toggle for HAGS as well :)

**Comment by RedDot-3ND7355** [comment]
Fixed and added a new feature!

**Comment by gutko** [comment]
thank you!!!
